INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE) VALUES ('Smartwatch', 'Samsung Galaxy Watch 4', 20000.00);
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE) VALUES ('Headphones', 'Sony WH1000XM4', 35000.00);
