version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: day31-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: day31
      MYSQL_USER: day31user
      MYSQL_PASSWORD: day31pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: day31-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/day31?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: day31user
      SPRING_DATASOURCE_PASSWORD: day31pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect


volumes:
  db_data:
