INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, PRICE) VALUES ('SKU-001', 'Demo Product A', 'Seeded product A', 99.99);
INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, PRICE) VALUES ('SKU-002', 'Demo Product B', 'Seeded product B', 49.50);
